### ISSUE TITLE
Traceback (most recent call last):   File "smartBugs.py", line 13, in <module>     from src.docker_api.docker_api import analyse_files ModuleNotFoundError: No module named 'src.docker_api'

### ISSUE THREAD

**Issue by LORDCYBERGOD** [smartbugs/smartbugs#107] opened 2022-02-12 04:32 UTC
I made many changes  in a program still I am facing Traceback (most recent call last):
  File "smartBugs.py", line 13, in <module>
    from src.docker_api.docker_api import analyse_files
ModuleNotFoundError: No module named 'src.docker_api'

**Comment by gsalzer** [comment] 2022-02-12 17:15
You do not provide any information about which branch you are referring to (`master`, `bytecode`?) and what you changed (my crystal ball doesn't show any of your *many changes in a program*), but the problem is probably easy to resolve. According to the error message, the directory from where you start your Python program does not contain `src/docker_api`. Please check.

Either you start the program from the wrong directory, or you have checked out the `bytecode` branch, but use `smartBugs.py` from the `master` branch (or your own modified copy of it). In the `bytecode` branch, you need

```python
    from src.execution.docker_api import analyse_files
```

But I'm not sure that the code in the `bytecode` branch still does what you are used to from the `master` branch.

**Comment by gsalzer** [comment] 2022-02-28 09:01
I'm closing the issue as there is not enough information available that would allow us to analyze the problem. Please reopen the issue if needed, providing more details.

**Closed by gsalzer** 2022-02-28 09:01 UTC
Labels: question
